### ISSUE TITLE
Routopsy can't insert rule into chain DOCKER-USER

### ISSUE THREAD

**Issue by caster0x00** [sensepost/routopsy#5]
Hi! Routopsy for some reason cannot add the necessary DNAT rule to the DOCKER-USER chain. What could be the problem that I might have missed?
![issue](https://user-images.githubusercontent.com/88490676/151658512-0ec33218-5cec-4158-91f9-59cfe7da3f91.png)

**Comment by kockakepzo** [comment]
hello, could you provide an update what was the solution? I tried to export the XTABLES_LIBDIR to the libdir on ubuntu but got the same error.

**Comment by rainomm** [comment]
> hello, could you provide an update what was the solution? I tried to export the XTABLES_LIBDIR to the libdir on ubuntu but got the same error.

Hi. Been struggling with the same error for a while. Eventually the culprit was Ubuntu 22.04 where they have changed firewall backend from iptables to nftables
Fix was to switch it back:

```
update-alternatives --query iptables
update-alternatives --set iptables /usr/sbin/iptables-legacy  
update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy  
```
